// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package service

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type userInfo_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var UserInfoBinding = userInfo_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 5668241497911038766,
}

// UserInfo_ contains type-based Property helpers to facilitate some common operations such as Queries.
var UserInfo_ = struct {
	Id        *objectbox.PropertyUint64
	Name      *objectbox.PropertyString
	About     *objectbox.PropertyString
	UserID    *objectbox.PropertyString
	SessionID *objectbox.PropertyString
	ChatID    *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &UserInfoBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &UserInfoBinding.Entity,
		},
	},
	About: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &UserInfoBinding.Entity,
		},
	},
	UserID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &UserInfoBinding.Entity,
		},
	},
	SessionID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &UserInfoBinding.Entity,
		},
	},
	ChatID: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &UserInfoBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (userInfo_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (userInfo_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("UserInfo", 1, 5668241497911038766)
	model.Property("Id", 6, 1, 6772883480447739477)
	model.PropertyFlags(1)
	model.Property("Name", 9, 2, 7540738820591150347)
	model.Property("About", 9, 3, 2055954203675394069)
	model.Property("UserID", 9, 4, 871741141910924249)
	model.Property("SessionID", 9, 5, 8630392538375525116)
	model.Property("ChatID", 6, 6, 7332245039961824802)
	model.EntityLastPropertyId(6, 7332245039961824802)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (userInfo_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*UserInfo).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (userInfo_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*UserInfo).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (userInfo_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (userInfo_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*UserInfo)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetAbout = fbutils.CreateStringOffset(fbb, obj.About)
	var offsetUserID = fbutils.CreateStringOffset(fbb, obj.UserID)
	var offsetSessionID = fbutils.CreateStringOffset(fbb, obj.SessionID)

	// build the FlatBuffers object
	fbb.StartObject(6)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 5, obj.ChatID)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetAbout)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetUserID)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetSessionID)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (userInfo_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'UserInfo' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &UserInfo{
		Id:        propId,
		ChatID:    fbutils.GetInt64Slot(table, 14),
		Name:      fbutils.GetStringSlot(table, 6),
		About:     fbutils.GetStringSlot(table, 8),
		UserID:    fbutils.GetStringSlot(table, 10),
		SessionID: fbutils.GetStringSlot(table, 12),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (userInfo_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*UserInfo, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (userInfo_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*UserInfo), nil)
	}
	return append(slice.([]*UserInfo), object.(*UserInfo))
}

// Box provides CRUD access to UserInfo objects
type UserInfoBox struct {
	*objectbox.Box
}

// BoxForUserInfo opens a box of UserInfo objects
func BoxForUserInfo(ob *objectbox.ObjectBox) *UserInfoBox {
	return &UserInfoBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the UserInfo.Id property on the passed object will be assigned the new ID as well.
func (box *UserInfoBox) Put(object *UserInfo) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the UserInfo.Id property on the passed object will be assigned the new ID as well.
func (box *UserInfoBox) Insert(object *UserInfo) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *UserInfoBox) Update(object *UserInfo) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *UserInfoBox) PutAsync(object *UserInfo) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the UserInfo.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the UserInfo.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *UserInfoBox) PutMany(objects []*UserInfo) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *UserInfoBox) Get(id uint64) (*UserInfo, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*UserInfo), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *UserInfoBox) GetMany(ids ...uint64) ([]*UserInfo, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*UserInfo), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *UserInfoBox) GetManyExisting(ids ...uint64) ([]*UserInfo, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*UserInfo), nil
}

// GetAll reads all stored objects
func (box *UserInfoBox) GetAll() ([]*UserInfo, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*UserInfo), nil
}

// Remove deletes a single object
func (box *UserInfoBox) Remove(object *UserInfo) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *UserInfoBox) RemoveMany(objects ...*UserInfo) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the UserInfo_ struct to create conditions.
// Keep the *UserInfoQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *UserInfoBox) Query(conditions ...objectbox.Condition) *UserInfoQuery {
	return &UserInfoQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the UserInfo_ struct to create conditions.
// Keep the *UserInfoQuery if you intend to execute the query multiple times.
func (box *UserInfoBox) QueryOrError(conditions ...objectbox.Condition) (*UserInfoQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &UserInfoQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See UserInfoAsyncBox for more information.
func (box *UserInfoBox) Async() *UserInfoAsyncBox {
	return &UserInfoAsyncBox{AsyncBox: box.Box.Async()}
}

// UserInfoAsyncBox provides asynchronous operations on UserInfo objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type UserInfoAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForUserInfo creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use UserInfoBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForUserInfo(ob *objectbox.ObjectBox, timeoutMs uint64) *UserInfoAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &UserInfoAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *UserInfoAsyncBox) Put(object *UserInfo) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *UserInfoAsyncBox) Insert(object *UserInfo) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *UserInfoAsyncBox) Update(object *UserInfo) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *UserInfoAsyncBox) Remove(object *UserInfo) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all UserInfo which Id is either 42 or 47:
//
// box.Query(UserInfo_.Id.In(42, 47)).Find()
type UserInfoQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *UserInfoQuery) Find() ([]*UserInfo, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*UserInfo), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *UserInfoQuery) Offset(offset uint64) *UserInfoQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *UserInfoQuery) Limit(limit uint64) *UserInfoQuery {
	query.Query.Limit(limit)
	return query
}

type flowStep_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var FlowStepBinding = flowStep_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 6008137059588212786,
}

// FlowStep_ contains type-based Property helpers to facilitate some common operations such as Queries.
var FlowStep_ = struct {
	Id     *objectbox.PropertyUint64
	ChatID *objectbox.PropertyInt64
	Step   *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &FlowStepBinding.Entity,
		},
	},
	ChatID: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &FlowStepBinding.Entity,
		},
	},
	Step: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &FlowStepBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (flowStep_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (flowStep_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("FlowStep", 2, 6008137059588212786)
	model.Property("Id", 6, 1, 734413594985093942)
	model.PropertyFlags(1)
	model.Property("ChatID", 6, 2, 844194218502871065)
	model.Property("Step", 9, 3, 7794280561810551578)
	model.EntityLastPropertyId(3, 7794280561810551578)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (flowStep_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*FlowStep).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (flowStep_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*FlowStep).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (flowStep_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (flowStep_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*FlowStep)
	var offsetStep = fbutils.CreateStringOffset(fbb, obj.Step)

	// build the FlatBuffers object
	fbb.StartObject(3)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, obj.ChatID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetStep)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (flowStep_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'FlowStep' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &FlowStep{
		Id:     propId,
		ChatID: fbutils.GetInt64Slot(table, 6),
		Step:   fbutils.GetStringSlot(table, 8),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (flowStep_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*FlowStep, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (flowStep_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*FlowStep), nil)
	}
	return append(slice.([]*FlowStep), object.(*FlowStep))
}

// Box provides CRUD access to FlowStep objects
type FlowStepBox struct {
	*objectbox.Box
}

// BoxForFlowStep opens a box of FlowStep objects
func BoxForFlowStep(ob *objectbox.ObjectBox) *FlowStepBox {
	return &FlowStepBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FlowStep.Id property on the passed object will be assigned the new ID as well.
func (box *FlowStepBox) Put(object *FlowStep) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FlowStep.Id property on the passed object will be assigned the new ID as well.
func (box *FlowStepBox) Insert(object *FlowStep) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *FlowStepBox) Update(object *FlowStep) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *FlowStepBox) PutAsync(object *FlowStep) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the FlowStep.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the FlowStep.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *FlowStepBox) PutMany(objects []*FlowStep) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *FlowStepBox) Get(id uint64) (*FlowStep, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*FlowStep), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *FlowStepBox) GetMany(ids ...uint64) ([]*FlowStep, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FlowStep), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *FlowStepBox) GetManyExisting(ids ...uint64) ([]*FlowStep, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FlowStep), nil
}

// GetAll reads all stored objects
func (box *FlowStepBox) GetAll() ([]*FlowStep, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*FlowStep), nil
}

// Remove deletes a single object
func (box *FlowStepBox) Remove(object *FlowStep) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *FlowStepBox) RemoveMany(objects ...*FlowStep) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the FlowStep_ struct to create conditions.
// Keep the *FlowStepQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *FlowStepBox) Query(conditions ...objectbox.Condition) *FlowStepQuery {
	return &FlowStepQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the FlowStep_ struct to create conditions.
// Keep the *FlowStepQuery if you intend to execute the query multiple times.
func (box *FlowStepBox) QueryOrError(conditions ...objectbox.Condition) (*FlowStepQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &FlowStepQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See FlowStepAsyncBox for more information.
func (box *FlowStepBox) Async() *FlowStepAsyncBox {
	return &FlowStepAsyncBox{AsyncBox: box.Box.Async()}
}

// FlowStepAsyncBox provides asynchronous operations on FlowStep objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type FlowStepAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForFlowStep creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use FlowStepBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForFlowStep(ob *objectbox.ObjectBox, timeoutMs uint64) *FlowStepAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &FlowStepAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *FlowStepAsyncBox) Put(object *FlowStep) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *FlowStepAsyncBox) Insert(object *FlowStep) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *FlowStepAsyncBox) Update(object *FlowStep) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *FlowStepAsyncBox) Remove(object *FlowStep) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all FlowStep which Id is either 42 or 47:
//
// box.Query(FlowStep_.Id.In(42, 47)).Find()
type FlowStepQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *FlowStepQuery) Find() ([]*FlowStep, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*FlowStep), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *FlowStepQuery) Offset(offset uint64) *FlowStepQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *FlowStepQuery) Limit(limit uint64) *FlowStepQuery {
	query.Query.Limit(limit)
	return query
}
